document.body.classList.add('js-ready');
const CHANNEL_URL = 'https://www.youtube.com/@paint_pong';

// ---------- capability-aware motion ----------
const prefersReduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const isTouch = matchMedia('(pointer: coarse)').matches || innerWidth < 850;

const cursorGlow = document.querySelector('.cursor-glow');
if (cursorGlow && !isTouch && !prefersReduced) {
  let pointerX = innerWidth / 2, pointerY = innerHeight / 2, glowX = pointerX, glowY = pointerY;
  window.addEventListener('pointermove', e => { pointerX=e.clientX; pointerY=e.clientY; }, {passive:true});
  const animateGlow=()=>{glowX+=(pointerX-glowX)*.09;glowY+=(pointerY-glowY)*.09;cursorGlow.style.left=glowX+'px';cursorGlow.style.top=glowY+'px';requestAnimationFrame(animateGlow)};
  animateGlow();
} else if (cursorGlow) cursorGlow.style.display='none';

if (!isTouch && !prefersReduced) {
  for(const el of document.querySelectorAll('.magnetic')){
    el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2);el.style.transform=`translate(${x*.07}px,${y*.07}px)`},{passive:true});
    el.addEventListener('pointerleave',()=>el.style.transform='');
  }
  for(const card of document.querySelectorAll('.tilt-card')){
    card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(850px) rotateX(${y*-4}deg) rotateY(${x*5}deg) translateY(-2px)`},{passive:true});
    card.addEventListener('pointerleave',()=>card.style.transform='');
  }
}

// ---------- calm ambient canvas on desktop; CSS ambient field on touch ----------
const canvas=document.getElementById('particles');
if (canvas && !isTouch && !prefersReduced) {
  const ctx=canvas.getContext('2d'); let dots=[];
  function resizeCanvas(){
    const dpr=Math.min(devicePixelRatio||1,1.75); canvas.width=innerWidth*dpr; canvas.height=innerHeight*dpr; canvas.style.width=innerWidth+'px'; canvas.style.height=innerHeight+'px'; ctx.setTransform(dpr,0,0,dpr,0,0);
    dots=Array.from({length:Math.min(55,Math.floor(innerWidth/26))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.12,vy:(Math.random()-.5)*.12,r:Math.random()*.9+.25}));
  }
  function loop(){ctx.clearRect(0,0,innerWidth,innerHeight);for(const d of dots){d.x=(d.x+d.vx+innerWidth)%innerWidth;d.y=(d.y+d.vy+innerHeight)%innerHeight;ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fillStyle='rgba(180,205,225,.24)';ctx.fill()}requestAnimationFrame(loop)}
  resizeCanvas();loop();addEventListener('resize',resizeCanvas,{passive:true});
} else if (canvas) canvas.style.display='none';

// Reveal works reliably on touch too; on very slow browsers avoid keeping elements hidden.
const revealItems=[...document.querySelectorAll('.reveal')];
const revealIO = new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');revealIO.unobserve(e.target)}}),{threshold:isTouch?.04:.12,rootMargin:'0px 0px -8% 0px'});
revealItems.forEach((el,i)=>{el.style.setProperty('--reveal-index',i%8);revealIO.observe(el)});
setTimeout(()=>revealItems.forEach(el=>el.classList.add('in')),4500);

// active navigation + scroll progress
const sections=[...document.querySelectorAll('main section[id]')], navLinks=[...document.querySelectorAll('.nav-link')], progress=document.querySelector('.scroll-progress span');
addEventListener('scroll',()=>{const total=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=(total?scrollY/total*100:0)+'%';let current='home';for(const s of sections){if(scrollY+innerHeight*.3>=s.offsetTop)current=s.id}navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current));},{passive:true});
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();

// ---------- latest YouTube upload generated by GitHub Actions ----------
async function loadLatest(){
  const card=document.getElementById('latest-video'), thumb=document.getElementById('latest-thumbnail'), title=document.getElementById('latest-title'), date=document.getElementById('latest-date');
  if(!card||!thumb||!title||!date)return;
  try{
    const res=await fetch(`latest.json?ts=${Date.now()}`,{cache:'no-store'}); if(!res.ok)throw new Error('feed unavailable');
    const v=await res.json(); if(!v?.id)throw new Error('empty feed');
    card.href=v.url||`https://www.youtube.com/watch?v=${v.id}`; thumb.src=v.thumbnail||`https://i.ytimg.com/vi/${v.id}/hqdefault.jpg`; title.textContent=v.title||'Последняя работа';
    date.textContent=v.published?new Date(v.published).toLocaleDateString('ru-RU',{day:'2-digit',month:'long',year:'numeric'}).toUpperCase():'LATEST UPLOAD';
  }catch(e){title.textContent='Новая работа — на YouTube';date.textContent='ОТКРОЙТЕ КАНАЛ';}
}
loadLatest();

// ---------- audio-reactive record ----------
const audio=document.getElementById('portfolio-audio'), viz=document.getElementById('audio-visualizer'), status=document.getElementById('audio-status');
let audioCtx, analyser, sourceNode, dataArray, vizRAF;
function setupAudio(){
  if(audioCtx || !audio)return;
  try{
    audioCtx=new (window.AudioContext||window.webkitAudioContext)(); analyser=audioCtx.createAnalyser(); analyser.fftSize=256; analyser.smoothingTimeConstant=.82; dataArray=new Uint8Array(analyser.frequencyBinCount);
    sourceNode=audioCtx.createMediaElementSource(audio); sourceNode.connect(analyser); analyser.connect(audioCtx.destination);
    drawAudio();
  }catch(e){status.textContent='AUDIO PLAYER READY';}
}
function drawAudio(){
  if(!viz)return; const dpr=Math.min(devicePixelRatio||1,2), rect=viz.getBoundingClientRect(); if(!rect.width||!rect.height){vizRAF=requestAnimationFrame(drawAudio);return}
  if(viz.width!==Math.round(rect.width*dpr)||viz.height!==Math.round(rect.height*dpr)){viz.width=rect.width*dpr;viz.height=rect.height*dpr;}
  const c=viz.getContext('2d'); c.setTransform(dpr,0,0,dpr,0,0); c.clearRect(0,0,rect.width,rect.height);
  const cx=rect.width/2,cy=rect.height/2,maxR=Math.min(rect.width,rect.height)*.43;
  if(analyser){analyser.getByteFrequencyData(dataArray);let bass=0;for(let i=0;i<12;i++)bass+=dataArray[i]||0;bass=(bass/12)/255;} else bass=.08;
  const bars=Math.min(72,dataArray?.length||72);
  for(let i=0;i<bars;i++){
    const a=(i/bars)*Math.PI*2, idx=Math.floor(i*(dataArray?.length||1)/bars), amp=(dataArray?.[idx]||14)/255;
    const inner=maxR*.68, outer=inner+amp*maxR*.48+bass*8;
    const x1=cx+Math.cos(a)*inner, y1=cy+Math.sin(a)*inner, x2=cx+Math.cos(a)*outer, y2=cy+Math.sin(a)*outer;
    c.beginPath(); c.moveTo(x1,y1); c.lineTo(x2,y2); c.lineWidth=1.25+amp*1.4; c.strokeStyle=i%9===0?'rgba(216,122,57,.72)':'rgba(75,180,255,.54)'; c.stroke();
  }
  c.beginPath();c.arc(cx,cy,maxR*(.56+bass*.06),0,Math.PI*2);c.strokeStyle=`rgba(255,255,255,${.08+bass*.12})`;c.lineWidth=1;c.stroke();
  vizRAF=requestAnimationFrame(drawAudio);
}
if(audio){
  audio.addEventListener('play',()=>{setupAudio(); if(audioCtx?.state==='suspended')audioCtx.resume(); if(status)status.textContent='PLAYING · LIVE SPECTRUM';});
  audio.addEventListener('pause',()=>{if(status)status.textContent='PAUSED · PAINT_PONG ORIGINAL'});
  audio.addEventListener('error',()=>{if(status)status.textContent='AUDIO FILE READY';});
  drawAudio();
}
