document.body.classList.add('js-ready');
const CHANNEL_URL = 'https://www.youtube.com/@paint_pong';

// ---------- capability-aware motion ----------
const prefersReduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const isTouch = matchMedia('(pointer: coarse)').matches || innerWidth < 850;

const cursorGlow = document.querySelector('.cursor-glow');
if (cursorGlow && !isTouch && !prefersReduced) {
  let pointerX = innerWidth / 2, pointerY = innerHeight / 2, glowX = pointerX, glowY = pointerY;
  window.addEventListener('pointermove', e => { pointerX=e.clientX; pointerY=e.clientY; }, {passive:true});
  const animateGlow=()=>{glowX+=(pointerX-glowX)*.09;glowY+=(pointerY-glowY)*.09;cursorGlow.style.left=glowX+'px';cursorGlow.style.top=glowY+'px';requestAnimationFrame(animateGlow)};
  animateGlow();
} else if (cursorGlow) cursorGlow.style.display='none';

if (!isTouch && !prefersReduced) {
  for(const el of document.querySelectorAll('.magnetic')){
    el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2);el.style.transform=`translate(${x*.07}px,${y*.07}px)`},{passive:true});
    el.addEventListener('pointerleave',()=>el.style.transform='');
  }
  for(const card of document.querySelectorAll('.tilt-card')){
    card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(850px) rotateX(${y*-4}deg) rotateY(${x*5}deg) translateY(-2px)`},{passive:true});
    card.addEventListener('pointerleave',()=>card.style.transform='');
  }
}

// ---------- calm ambient canvas on desktop; CSS ambient field on touch ----------
const canvas=document.getElementById('particles');
if (canvas && !isTouch && !prefersReduced) {
  const ctx=canvas.getContext('2d'); let dots=[];
  function resizeCanvas(){
    const dpr=Math.min(devicePixelRatio||1,1.75); canvas.width=innerWidth*dpr; canvas.height=innerHeight*dpr; canvas.style.width=innerWidth+'px'; canvas.style.height=innerHeight+'px'; ctx.setTransform(dpr,0,0,dpr,0,0);
    dots=Array.from({length:Math.min(55,Math.floor(innerWidth/26))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.12,vy:(Math.random()-.5)*.12,r:Math.random()*.9+.25}));
  }
  function loop(){ctx.clearRect(0,0,innerWidth,innerHeight);for(const d of dots){d.x=(d.x+d.vx+innerWidth)%innerWidth;d.y=(d.y+d.vy+innerHeight)%innerHeight;ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fillStyle='rgba(180,205,225,.24)';ctx.fill()}requestAnimationFrame(loop)}
  resizeCanvas();loop();addEventListener('resize',resizeCanvas,{passive:true});
} else if (canvas) canvas.style.display='none';

// Reveal works reliably on touch too; on very slow browsers avoid keeping elements hidden.
const revealItems=[...document.querySelectorAll('.reveal')];
const revealIO = new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');revealIO.unobserve(e.target)}}),{threshold:isTouch?.04:.12,rootMargin:'0px 0px -8% 0px'});
revealItems.forEach((el,i)=>{el.style.setProperty('--reveal-index',i%8);revealIO.observe(el)});
setTimeout(()=>revealItems.forEach(el=>el.classList.add('in')),4500);

// active navigation + scroll progress
const sections=[...document.querySelectorAll('main section[id]')], navLinks=[...document.querySelectorAll('.nav-link')], progress=document.querySelector('.scroll-progress span');
addEventListener('scroll',()=>{const total=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=(total?scrollY/total*100:0)+'%';let current='home';for(const s of sections){if(scrollY+innerHeight*.3>=s.offsetTop)current=s.id}navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current));},{passive:true});
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();

// ---------- latest YouTube upload generated by GitHub Actions ----------
async function loadLatest(){
  const card=document.getElementById('latest-video'), thumb=document.getElementById('latest-thumbnail'), title=document.getElementById('latest-title'), date=document.getElementById('latest-date');
  if(!card||!thumb||!title||!date)return;
  try{
    const res=await fetch(`latest.json?ts=${Date.now()}`,{cache:'no-store'}); if(!res.ok)throw new Error('feed unavailable');
    const v=await res.json(); if(!v?.id)throw new Error('empty feed');
    card.href=v.url||`https://www.youtube.com/watch?v=${v.id}`; thumb.src=v.thumbnail||`https://i.ytimg.com/vi/${v.id}/hqdefault.jpg`; title.textContent=v.title||'Последняя работа';
    date.textContent=v.published?new Date(v.published).toLocaleDateString('ru-RU',{day:'2-digit',month:'long',year:'numeric'}).toUpperCase():'LATEST UPLOAD';
  }catch(e){title.textContent='Новая работа — на YouTube';date.textContent='ОТКРОЙТЕ КАНАЛ';}
}
loadLatest();

// ---------- audio-reactive record ----------
const audio=document.getElementById('portfolio-audio'), viz=document.getElementById('audio-visualizer'), status=document.getElementById('audio-status');
let audioCtx, analyser, sourceNode, dataArray, vizRAF;
function setupAudio(){
  if(audioCtx || !audio)return;
  try{
    audioCtx=new (window.AudioContext||window.webkitAudioContext)(); analyser=audioCtx.createAnalyser(); window.analyser=analyser; analyser.fftSize=256; analyser.smoothingTimeConstant=.82; dataArray=new Uint8Array(analyser.frequencyBinCount); window.dataArray=dataArray;
    sourceNode=audioCtx.createMediaElementSource(audio); sourceNode.connect(analyser); analyser.connect(audioCtx.destination);
    drawAudio();
  }catch(e){status.textContent='AUDIO PLAYER READY';}
}
function drawAudio(){
  if(!viz)return; const dpr=Math.min(devicePixelRatio||1,2), rect=viz.getBoundingClientRect(); if(!rect.width||!rect.height){vizRAF=requestAnimationFrame(drawAudio);return}
  if(viz.width!==Math.round(rect.width*dpr)||viz.height!==Math.round(rect.height*dpr)){viz.width=rect.width*dpr;viz.height=rect.height*dpr;}
  const c=viz.getContext('2d'); c.setTransform(dpr,0,0,dpr,0,0); c.clearRect(0,0,rect.width,rect.height);
  const cx=rect.width/2,cy=rect.height/2,maxR=Math.min(rect.width,rect.height)*.43;
  if(analyser){analyser.getByteFrequencyData(dataArray);let bass=0;for(let i=0;i<12;i++)bass+=dataArray[i]||0;bass=(bass/12)/255;} else bass=.08;
  const bars=Math.min(72,dataArray?.length||72);
  for(let i=0;i<bars;i++){
    const a=(i/bars)*Math.PI*2, idx=Math.floor(i*(dataArray?.length||1)/bars), amp=(dataArray?.[idx]||14)/255;
    const inner=maxR*.68, outer=inner+amp*maxR*.48+bass*8;
    const x1=cx+Math.cos(a)*inner, y1=cy+Math.sin(a)*inner, x2=cx+Math.cos(a)*outer, y2=cy+Math.sin(a)*outer;
    c.beginPath(); c.moveTo(x1,y1); c.lineTo(x2,y2); c.lineWidth=1.25+amp*1.4; c.strokeStyle=i%9===0?'rgba(216,122,57,.72)':'rgba(75,180,255,.54)'; c.stroke();
  }
  c.beginPath();c.arc(cx,cy,maxR*(.56+bass*.06),0,Math.PI*2);c.strokeStyle=`rgba(255,255,255,${.08+bass*.12})`;c.lineWidth=1;c.stroke();
  vizRAF=requestAnimationFrame(drawAudio);
}
if(audio){
  audio.addEventListener('play',()=>{setupAudio(); if(audioCtx?.state==='suspended')audioCtx.resume(); if(status)status.textContent='PLAYING · LIVE SPECTRUM';});
  audio.addEventListener('pause',()=>{if(status)status.textContent='PAUSED · PAINT_PONG ORIGINAL'});
  audio.addEventListener('error',()=>{if(status)status.textContent='AUDIO FILE READY';});
  drawAudio();
}

// ---------- interactive hero logo ----------
const logoStage = document.getElementById('hero-logo-stage');
const heroLogo = document.getElementById('hero-logo');
if (logoStage && heroLogo && !prefersReduced) {
  let raf = 0, targetRX = 0, targetRY = 0, currentRX = 0, currentRY = 0;
  const moveLogo = (clientX, clientY) => {
    const r = logoStage.getBoundingClientRect();
    const x = Math.max(-1,Math.min(1,(clientX - (r.left + r.width/2)) / (r.width/2)));
    const y = Math.max(-1,Math.min(1,(clientY - (r.top + r.height/2)) / (r.height/2)));
    targetRY = x * 8; targetRX = -y * 6;
    if (!raf) raf=requestAnimationFrame(function tick(){
      currentRX += (targetRX-currentRX)*.15; currentRY += (targetRY-currentRY)*.15;
      if(!logoStage.classList.contains('logo-droplet')) heroLogo.style.transform=`perspective(900px) rotateX(${currentRX}deg) rotateY(${currentRY}deg)`;
      if(Math.abs(targetRX-currentRX)+Math.abs(targetRY-currentRY)>.01) raf=requestAnimationFrame(tick); else raf=0;
    });
  };
  logoStage.addEventListener('pointermove',e=>moveLogo(e.clientX,e.clientY),{passive:true});
  logoStage.addEventListener('pointerleave',()=>moveLogo(logoStage.getBoundingClientRect().left+logoStage.offsetWidth/2,logoStage.getBoundingClientRect().top+logoStage.offsetHeight/2));
  logoStage.addEventListener('click',e=>{
    const filterMap=document.querySelector('#liquidLogo feDisplacementMap');
    logoStage.classList.remove('logo-droplet'); void logoStage.offsetWidth; logoStage.classList.add('logo-droplet');
    if(filterMap){
      const start=performance.now(), dur=860;
      const tick=t=>{const q=Math.min(1,(t-start)/dur); const pulse=Math.sin(q*Math.PI); filterMap.setAttribute('scale',(pulse*24).toFixed(2)); if(q<1) requestAnimationFrame(tick); else filterMap.setAttribute('scale','0')};
      requestAnimationFrame(tick);
    }
    setTimeout(()=>logoStage.classList.remove('logo-droplet'),950);
  });
}

// ---------- character select / smooth PNG carousel ----------
const characterData=[['bogle.png','Bogle'],['chacatolo.png','Chacatolo'],["cre'eepstalic.png","Cre'eepstalic"],['knighTss.png','KnighTss'],['kvaraban.png','Kvaraban'],['panitoor.png','Panitoor'],['werdo.png','Werdo'],["zom'jelly.png","Zom'jelly"]];
const picker=document.getElementById('character-picker'), stage=document.getElementById('character-stage');
const currentImg=document.getElementById('character-current'), prevImg=document.getElementById('character-prev'), nextImg=document.getElementById('character-next');
const mainLink=document.getElementById('character-main'), indexEl=document.getElementById('character-index'), nameEl=document.getElementById('character-name'), dots=document.getElementById('picker-dots');
let characterIndex=0, charAnimating=false;
function charPath(i){return 'assets/characters/'+encodeURIComponent(characterData[i][0]).replace(/%2F/g,'/').replace(/%27/g,"'");}
function paintCharacter(i){
  characterIndex=(i+characterData.length)%characterData.length;
  const prev=(characterIndex-1+characterData.length)%characterData.length,next=(characterIndex+1)%characterData.length;
  currentImg.src=charPath(characterIndex); currentImg.alt=characterData[characterIndex][1]; prevImg.src=charPath(prev); nextImg.src=charPath(next);
  mainLink.href=charPath(characterIndex); indexEl.textContent=String(characterIndex+1).padStart(2,'0')+' / '+String(characterData.length).padStart(2,'0'); nameEl.textContent=characterData[characterIndex][1];
  dots?.querySelectorAll('.picker-dot').forEach((d,j)=>d.classList.toggle('active',j===characterIndex));
}
function renderCharacter(target, direction=1, animate=true){
  if(!picker||!stage||charAnimating)return;
  target=(target+characterData.length)%characterData.length;
  if(!animate){paintCharacter(target);return;}
  charAnimating=true;
  const oldSrc=currentImg.src, oldAlt=currentImg.alt;
  const ghost=document.createElement('img'); ghost.className='char-travel-ghost'; ghost.src=oldSrc; ghost.alt='';
  ghost.style.cssText=`position:absolute;width:${currentImg.getBoundingClientRect().width}px;height:${currentImg.getBoundingClientRect().height}px;object-fit:contain;z-index:6;left:50%;top:50%;transform:translate(-50%,-50%);pointer-events:none;`;
  stage.appendChild(ghost);
  currentImg.style.opacity='0';
  paintCharacter(target);
  stage.classList.remove('char-direction-prev','char-direction-next'); void stage.offsetWidth;
  stage.classList.add(direction>0?'char-direction-next':'char-direction-prev');
  currentImg.classList.remove('char-enter-next','char-enter-prev'); void currentImg.offsetWidth; currentImg.classList.add(direction>0?'char-enter-next':'char-enter-prev');
  ghost.animate([
    {transform:'translate(-50%,-50%) scale(1)',opacity:1,filter:'blur(0)'},
    {transform:`translate(calc(-50% ${direction>0?'-':'+'} 32%),-50%) scale(.72)`,opacity:.05,filter:'blur(5px)'}
  ],{duration:650,easing:'cubic-bezier(.16,.78,.18,1)',fill:'forwards'}).onfinish=()=>{ghost.remove();currentImg.style.opacity='';currentImg.classList.remove('char-enter-next','char-enter-prev');stage.classList.remove('char-direction-prev','char-direction-next');charAnimating=false;};
}
if(picker&&dots){
  characterData.forEach((_,i)=>{const b=document.createElement('button');b.className='picker-dot';b.type='button';b.setAttribute('aria-label','Персонаж '+(i+1));b.addEventListener('click',()=>renderCharacter(i,i>characterIndex?1:-1));dots.appendChild(b)});
  paintCharacter(0);
  document.querySelector('.picker-prev')?.addEventListener('click',()=>renderCharacter(characterIndex-1,-1));
  document.querySelector('.picker-next')?.addEventListener('click',()=>renderCharacter(characterIndex+1,1));
  let sx=0; picker.addEventListener('touchstart',e=>sx=e.changedTouches[0].clientX,{passive:true}); picker.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45)renderCharacter(characterIndex+(dx<0?1:-1),dx<0?1:-1)},{passive:true});
}

// ---------- animation section: wake the rig when entering viewport ----------
const animationSection=document.getElementById('animation');
if(animationSection){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting) animationSection.classList.add('in-view');}),{threshold:.2});io.observe(animationSection)}

// ---------- youtube ambient particles ----------
const ytField=document.getElementById('youtube-particle-field');
if(ytField && !prefersReduced){
  const wave=document.createElement('span'); wave.className='yt-wave'; ytField.appendChild(wave);
  const count=window.innerWidth<700?12:28;
  for(let i=0;i<count;i++){const p=document.createElement('span');p.className='yt-particle';p.style.left=(Math.random()*100)+'%';p.style.top=(8+Math.random()*82)+'%';p.style.setProperty('--x',((Math.random()-.5)*90)+'px');p.style.setProperty('--y',((Math.random()-.5)*70)+'px');p.style.setProperty('--d',(4+Math.random()*6)+'s');p.style.animationDelay=(-Math.random()*5)+'s';ytField.appendChild(p)}
}



// ---------- bilingual UI ----------
const translations={
  ru:{'nav.home':'Главная','nav.design':'Дизайн','nav.animation':'Анимация','nav.music':'Музыка','nav.youtube':'YouTube','nav.contact':'CONTACT / WORK','hero.eyebrow':'DIGITAL ARTIST · CREATIVE GENERALIST','hero.sub':'Создаю персонажей, миры, анимации, музыку и композитинг — соединяя визуальный дизайн с движением и звуком.','hero.work':'Смотреть работы','about.eyebrow':'WHO IS PAINT_PONG?','about.title1':'Один автор.','about.title2':'Много медиа.','about.p1':'Paint_Pong — независимый автор, который работает на стыке иллюстрации, анимации, дизайна, композитинга и музыки.','about.p2':'Вместо одной специализации я собираю проекты целиком: от идеи и визуального языка до движения, звука и финального композа.','design.eyebrow':'SELECTED VISUALS','design.title':'Дизайн','design.characters':'Персонажи','design.biomes':'Биомы','animation.eyebrow':'MOTION / STORY','animation.title':'Анимация','music.eyebrow':'AUDIO / SOUND','music.title':'Музыка','youtube.eyebrow':'LATEST FROM THE CHANNEL','youtube.title':'YouTube','youtube.latest1':'Последняя работа','youtube.latest2':'Paint_Pong','youtube.open':'Открыть канал','footer.top':'BACK TO TOP ↑'},
  en:{'nav.home':'Home','nav.design':'Design','nav.animation':'Animation','nav.music':'Music','nav.youtube':'YouTube','nav.contact':'CONTACT / WORK','hero.eyebrow':'DIGITAL ARTIST · CREATIVE GENERALIST','hero.sub':'I create characters, worlds, animation, music and compositing — connecting visual design with movement and sound.','hero.work':'View work','about.eyebrow':'WHO IS PAINT_PONG?','about.title1':'One creator.','about.title2':'Many media.','about.p1':'Paint_Pong is an independent creator working across illustration, animation, design, compositing and music.','about.p2':'Instead of one specialty, I build projects end-to-end: from the idea and visual language to motion, sound and final compositing.','design.eyebrow':'SELECTED VISUALS','design.title':'Design','design.characters':'Characters','design.biomes':'Biomes','animation.eyebrow':'MOTION / STORY','animation.title':'Animation','music.eyebrow':'AUDIO / SOUND','music.title':'Music','youtube.eyebrow':'LATEST FROM THE CHANNEL','youtube.title':'YouTube','youtube.latest1':'Latest work','youtube.latest2':'Paint_Pong','youtube.open':'Open channel','footer.top':'BACK TO TOP ↑'}
};
function applyLanguage(lang){
  const dict=translations[lang]||translations.ru;
  document.documentElement.lang=lang==='en'?'en':'ru';
  document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(dict[key]!=null)el.textContent=dict[key]});
  const toggle=document.getElementById('lang-toggle');
  if(toggle)toggle.innerHTML=lang==='ru'?'<span class="lang-active">RU</span><span>EN</span>':'<span>RU</span><span class="lang-active">EN</span>';
  localStorage.setItem('paintpong-lang',lang);
}
const langToggle=document.getElementById('lang-toggle');
if(langToggle){let lang=localStorage.getItem('paintpong-lang')||'ru';applyLanguage(lang);langToggle.addEventListener('click',()=>applyLanguage((localStorage.getItem('paintpong-lang')||'ru')==='ru'?'en':'ru'));}

// ---------- biome cursor lens ----------
document.querySelectorAll('.biome-probe').forEach(card=>card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();card.style.setProperty('--mx',((e.clientX-r.left)/r.width*100)+'%');card.style.setProperty('--my',((e.clientY-r.top)/r.height*100)+'%')},{passive:true}));

// ================= V5 IMMERSIVE EXPERIENCE =================
(function immersiveUpgrade(){
  const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const touch = matchMedia('(pointer: coarse)').matches || innerWidth < 850;

  // Smooth scroll: Lenis + GSAP ScrollTrigger. Touch keeps native scrolling.
  if (!reduce && !touch && window.Lenis && window.gsap && window.ScrollTrigger) {
    gsap.registerPlugin(ScrollTrigger);
    const lenis = new Lenis({ lerp: 0.085, smoothWheel: true, wheelMultiplier: 0.9 });
    lenis.on('scroll', ScrollTrigger.update);
    gsap.ticker.add((time)=>lenis.raf(time*1000));
    gsap.ticker.lagSmoothing(0);
    window.paintPongLenis = lenis;
    gsap.utils.toArray('section').forEach((section)=>{
      gsap.to(section.querySelectorAll('.section-heading,.about-title,.about-text,.character-picker,.video-list,.music-layout,.youtube-feature'),{
        y: -18, ease:'none', scrollTrigger:{trigger:section,start:'top bottom',end:'bottom top',scrub:1.2}
      });
    });
    const story=document.querySelector('.biome-story');
    const track=story?.querySelector('.biome-story-track');
    if(story&&track){
      const distance=Math.max(0,track.scrollWidth-window.innerWidth*.72);
      gsap.to(track,{x:-distance,ease:'none',scrollTrigger:{trigger:story,start:'top 80%',end:'bottom 20%',scrub:1,pin:false,onUpdate:self=>{const chapters=[...track.children];chapters.forEach((c,i)=>c.classList.toggle('is-active',Math.abs(i/(chapters.length-1||1)-self.progress)<.18));}}});
    }
  }

  // Premium custom cursor with magnetic / PLAY state.
  if(!touch && !reduce){
    const cur=document.querySelector('.custom-cursor');
    if(cur){let x=innerWidth/2,y=innerHeight/2,tx=x,ty=y; const loop=()=>{x+=(tx-x)*.2;y+=(ty-y)*.2;cur.style.transform=`translate3d(${x}px,${y}px,0) translate(-50%,-50%)`;requestAnimationFrame(loop)};loop();
      addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY},{passive:true});
      document.querySelectorAll('a,button,.magnetic,.character-main').forEach(el=>{el.addEventListener('pointerenter',()=>cur.classList.add('is-hover'));el.addEventListener('pointerleave',()=>cur.classList.remove('is-hover'))});
      document.querySelectorAll('.video-row,.latest-video-card').forEach(el=>{el.addEventListener('pointerenter',()=>{cur.classList.add('is-play');cur.querySelector('b').textContent='PLAY'});el.addEventListener('pointerleave',()=>cur.classList.remove('is-play'))});
    }
  }

  // WebGL procedural background: reacts to audio when the player is active.
  const bg=document.getElementById('webgl-bg');
  if(bg && window.THREE && !reduce){
    const renderer=new THREE.WebGLRenderer({canvas:bg,alpha:true,antialias:true});
    renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6)); renderer.setSize(innerWidth,innerHeight,false);
    const scene=new THREE.Scene(), camera=new THREE.Camera();
    const uniforms={uTime:{value:0},uBass:{value:.03},uHigh:{value:.02},uRes:{value:new THREE.Vector2(innerWidth,innerHeight)}};
    const mat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,uniforms,vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position,1.0);}`,fragmentShader:`
      varying vec2 vUv; uniform float uTime; uniform float uBass; uniform float uHigh; uniform vec2 uRes;
      float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);} 
      float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);} 
      void main(){vec2 uv=vUv-.5;uv.x*=uRes.x/uRes.y;float t=uTime*.12;float n=noise(uv*3.0+vec2(t,-t*.7));float wave=sin(length(uv)*9.0-uTime*.55+n*3.0);float pulse=smoothstep(.0,.85,uBass)*(.12+.09*sin(uTime*2.0));float d=length(uv+vec2(sin(t*.7)*.08,cos(t*.5)*.05));float glow=exp(-5.0*abs(d-.25-pulse));float orb=exp(-10.0*d*d);vec3 c=vec3(.10,.20,.28)*(0.55+0.45*n)+vec3(.16,.45,.72)*(glow*.35+uHigh*.25)+vec3(.72,.25,.10)*(orb*.08+uBass*.12);float alpha=(.16+glow*.18+orb*.06)+uBass*.08;gl_FragColor=vec4(c,alpha);}`});
    const plane=new THREE.Mesh(new THREE.PlaneGeometry(2,2),mat); scene.add(plane); camera.position.z=1;
    const resize=()=>{renderer.setSize(innerWidth,innerHeight,false);uniforms.uRes.value.set(innerWidth,innerHeight)}; addEventListener('resize',resize,{passive:true});
    const audioEl=document.getElementById('portfolio-audio');
    function frame(t){uniforms.uTime.value=t*.001; const a=window.__ppAudioData; if(a){uniforms.uBass.value+=(a.bass-uniforms.uBass.value)*.12;uniforms.uHigh.value+=(a.high-uniforms.uHigh.value)*.08;document.body.style.setProperty('--audio-bass',a.bass)} renderer.render(scene,camera);requestAnimationFrame(frame)} requestAnimationFrame(frame);
  }

  // Couple existing analyser to the background.
  const originalDraw=window.drawAudio;
  // The existing audio visualizer remains the source of truth; read its analyser when possible.
  const audioEl=document.getElementById('portfolio-audio');
  if(audioEl){
    const sample=()=>{try{if(window.analyser&&window.dataArray){window.analyser.getByteFrequencyData(window.dataArray);let bass=0,high=0;for(let i=0;i<10;i++)bass+=window.dataArray[i]||0;for(let i=40;i<72;i++)high+=window.dataArray[i]||0;window.__ppAudioData={bass:(bass/10)/255,high:(high/32)/255}}}catch{} requestAnimationFrame(sample)};requestAnimationFrame(sample);
    audioEl.addEventListener('play',()=>document.body.classList.add('audio-live')); audioEl.addEventListener('pause',()=>document.body.classList.remove('audio-live'));
  }

  // Real Spine 3.8 Web Player. The uploaded Bogle export declares Spine 3.8.75,
  // so the matching 3.8 runtime is used and the idle animation is selected.
  const spineHost=document.getElementById('bogle-spine-player');
  if(spineHost && window.spine?.SpinePlayer){
    try{
      new spine.SpinePlayer('bogle-spine-player',{
        jsonUrl:'assets/spine/bogle/bogle.json',
        atlasUrl:'assets/spine/bogle/bogle.atlas',
        animation:'idle',
        loop:true,
        showControls:false,
        alpha:true,
        backgroundColor:'transparent',
        preserveViewport:true,
        viewport:{x:-180,y:-120,width:360,height:500},
        success:function(player){
          document.getElementById('bogle-spine-frame')?.classList.add('spine-ready');
        },
        error:function(){
          document.getElementById('bogle-spine-frame')?.classList.add('spine-error');
        }
      });
    }catch(e){
      document.getElementById('bogle-spine-frame')?.classList.add('spine-error');
    }
  }

  // Matter.js physical tool tags in About.
  const toolsCanvas=document.getElementById('matter-tools');
  if(toolsCanvas && window.Matter && !reduce){
    const {Engine,Render,Runner,Bodies,Composite,Mouse,MouseConstraint} = Matter;
    const wrap=toolsCanvas.parentElement; const resize=()=>{const r=wrap.getBoundingClientRect();toolsCanvas.width=r.width;toolsCanvas.height=r.height};resize();addEventListener('resize',resize,{passive:true});
    const engine=Engine.create(); engine.gravity.y=.95;
    const render=Render.create({canvas:toolsCanvas,engine,options:{width:toolsCanvas.width,height:toolsCanvas.height,wireframes:false,background:'transparent',pixelRatio:devicePixelRatio||1}});
    const labels=['FL Studio','Photoshop','Spine 2D','Moho','Blender','DaVinci'];
    const bodies=labels.map((label,i)=>{const w=88+(i%3)*14,h=30;const b=Bodies.rectangle(90+i*125,20+i*8,w,h,{restitution:.74,friction:.02,render:{fillStyle:'rgba(12,18,24,.72)',strokeStyle:'rgba(255,255,255,.14)',lineWidth:1}});b.label=label;return b});
    const ground=Bodies.rectangle(toolsCanvas.width/2,toolsCanvas.height+14,toolsCanvas.width,28,{isStatic:true,render:{fillStyle:'rgba(255,255,255,.02)'}});Composite.add(engine,[ground,...bodies]);
    const mouse=Mouse.create(toolsCanvas),mc=MouseConstraint.create(engine,{mouse,constraint:{stiffness:.16,render:{visible:false}}});Composite.add(engine,mc);Render.run(render);Runner.run(Runner.create(),engine);
    Matter.Events.on(render,'afterRender',()=>{const c=render.context; c.save(); c.font='700 9px Space Grotesk'; c.textAlign='center'; c.textBaseline='middle'; bodies.forEach(b=>{c.fillStyle='rgba(255,255,255,.74)';c.fillText(b.label,b.position.x,b.position.y+1)}); c.restore();});
  }

  // Lightweight liquid interaction on project thumbnails.
  if(!reduce){document.querySelectorAll('.image-thumb,.latest-media,.biome-probe').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();const x=e.clientX-r.left,y=e.clientY-r.top;el.style.setProperty('--hx',(x/r.width*100)+'%');el.style.setProperty('--hy',(y/r.height*100)+'%');el.style.setProperty('--lx',((x/r.width)-.5)*12+'px');el.style.setProperty('--ly',((y/r.height)-.5)*12+'px');el.classList.add('liquid-hover')},{passive:true});el.addEventListener('pointerleave',()=>el.classList.remove('liquid-hover'))})}
})();
